# Metadata for the plugin
plugin:
    # Global plugin attributes
    type: unknown                   # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Beispiel Plugin für SmartHomeNG v1.5 und höher'
        en: 'Sample plugin for SmartHomeNG v1.5 and up'
    maintainer: <autor>
#    tester:                         # Who tests this plugin?
    state: develop                  # change to ready when done with development
#    keywords: iot xyz
#    documentation: https://github.com/smarthomeNG/smarthome/wiki/CLI-Plugin        # url of documentation (wiki) page
#    support: https://knx-user-forum.de/forum/supportforen/smarthome-py

    version: 1.0.0                  # Plugin version (must match the version specified in __init__.py)
    sh_minversion: 1.8              # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
#    py_minversion: 3.6             # minimum Python version to use for this plugin
#    py_maxversion:                 # maximum Python version to use for this plugin (leave empty if latest)
    multi_instance: false           # plugin supports multi instance
    restartable: unknown
    classname: SipCall              # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml (enter 'parameters: NONE', if section should be empty)
    sip_user:
        type: str
        mandatory: true
        description:
            de: 'SIP User Name'
            en: 'SIP User Name'

    sip_user_password:
        type: str
        hide: true
        mandatory: true
        description:
            de: 'SIP User Passwort'
            en: 'SIP User Password'

    sip_gateway:
        type: ip
        mandatory: true
        description:
            de: 'SIP Gateway IP'
            en: 'SIP Gateway IP'

    sip_port:
        type: int
        default: 5060
        description:
            de: 'SIP Gateway Port'
            en: 'SIP Gateway Port'

    display_name:
        type: str
        default: None
        description:
            de: 'Anzeige im Display, falls unterschiedlich zum SIP Login'
            en: 'Set the display name, if different from SIP login'

    webif_pagelength:
        type: int
        valid_list:
          - -1
          - 0
          - 25
          - 50
          - 100
        description:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.
                 0 = automatisch, -1 = alle'
            en: 'Amount of items being listed in a web interface table per page by default.
                 0 = automatic, -1 = all'
        description_long:
            de: 'Anzahl an Items, die standardmäßig in einer Web Interface Tabelle pro Seite angezeigt werden.\n
                 Bei 0 wird die Tabelle automatisch an die Höhe des Browserfensters angepasst.\n
                 Bei -1 werden alle Tabelleneinträge auf einer Seite angezeigt.'
            en: 'Amount of items being listed in a web interface table per page by default.\n
                 0 adjusts the table height automatically based on the height of the browser windows.\n
                 -1 shows all table entries on one page.'

item_attributes:
    sipcall_extension:
        type: str
        description:
            de: Rufnummer, die angerufen werden soll
            en: number, which will be called

    sipcall_ring_time:
        type: int
        default: 10
        description:
            de: Dauer des Klingels bis zum Abbruch
            en: Duration of ringing

item_structs: NONE
    # Definition of item-structure templates for this plugin (enter 'item_structs: NONE', if section should be empty)

#item_attribute_prefixes:
    # Definition of item attributes that only have a common prefix (enter 'item_attribute_prefixes: NONE' or ommit this section, if section should be empty)
    # NOTE: This section should only be used, if really nessesary (e.g. for the stateengine plugin)

plugin_functions: NONE
    # Definition of plugin functions defined by this plugin (enter 'plugin_functions: NONE', if section should be empty)

logic_parameters: NONE
    # Definition of logic parameters defined by this plugin (enter 'logic_parameters: NONE', if section should be empty)
